import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Aistė Pilvinytė Wognsen',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="ml-8">
          {children}
        </div>
      </body>
    </html>
  )
}
